export const scrawlHints = [
    "Freezing your own head",
    "Making friends with your tapeworm",
    "A man who has lost his muffins",
    "Lost in IKEA",
    "Throwing the baby out with the bathwater",
    "Going out in a blaze of glory",
    "Burger nips",
    "Trust excercises",
    "DIY lobotomy",
    "Sexting",
    "Shaving the llama",
    "Sculpting the cactus",
    "Freestyle kazoo solo",
    "Awkward hug",
    "Butt chin",
    "Spontanious human combustion",
    "Bad babysitter",
    "Sharknado",
    "Fighting fire with fire",
    "Tasering a sloth",
    "Holiday in hell",
    "Haunted oven",
    "Dancing on someone's grave",
    "The world's biggest sneeze",
    "Putting make-up on an owl",
    "Sore loser",
    "Bronies",
    "Cereal killer",
    "Cleaning out your pipes",
    "Moobs",
    "Netflix and chill",
    "Dutch oven",
    "Cow tipping",
    "Terrified by butter",
    "Putting make-up on an owl",
    "The world's biggest sneeze",
    "Pathetic snowman",
    "Stranger danger!",
    "Staring contest",
    "Eye-wateringly strong pickles",
    "Full of soup",
    "OAP conga line",
    "Over-sized foam fingers",
    "Toenail fungus",
    "Riding a weasel",
    "Combing your hair with a hedgehog",
    "Unicorn rainbow fart",
    "Pet rock",
    "Really ugly baby",
    "You scratch my back, I'll scratch yours"
];