export const ScrawlCards = [
    "Screaming inside your heart",
    "Bum bongos",
    "Aztec sacrifice",
    "Making an onion cry",
    "Awkward family photo",
    "Drunk fly",
    "The ugly friend",
    "Fighting fire with fire",
    "Tasering a sloth",
    "A man hiding in a pram",
    "Side boob",
    "Playing the drums with bananas",
    "Cat orgy",
    "Spontaneous human combustion",
    "Butt chin",
    "Glued to the screen",
    "Blowing smoke up someon's ass",
    "Toddler beauty pageant",
    "Trapped in a phone box",
    "Putting make-up on an owl",
    "The world's biggest sneeze",
    "Dry humping",
    "Brain freeze",
    "Haunted Oven",
    "Dancing on someone's grave",
    "Amoeba disco",
    "Extreme breastfeeding",
    "Falling apart",
    "Pinnocchio the porn star",
    "Abducted by butterflies",
    "Choking on doughnuts",
    "Face-plant",
    "Mail order bride",
    "Brushing your tongue",
    "A very disappointing Christmas",
    "Photocopying your balls",
    "Forgetting how to eat",
    "Worm God",
    "Snail jockey",
    "Licking people's shoes",
    "Laughing your head off",
    "Crap parkour",
    "Badly trained dentist",
    "A bizarre gardening accident",
    "Pooing in a urinal",
    "Pathetic snowman",
    "Stranger danger!",
    "Holiday in Hell",
    "Bad babysitter",
    "Stud muffin",
    "The wispiest of moustaches",
    "Anal bleaching",
    "Kicking dicks",
    "Alcoholic house husband",
    "Frisbee decapitation",
    "Free Willy",
    "Cowboy wrestling",
    "Staring contest",
    "Eye-wateringly strong pickles",
    "Love handles",
    "Sausage fingers",
    "Killing two birds with one stone",
    "Toenail fungus",
    "Happy slap",
    "Pooing on a pigeon",
    "Polishing a turd",
    "Biting off more than you can chew",
    "Cereal killer",
    "Cleaing out your pipes",
    "Costing an arm and a leg",
    "Fear of toilets",
    "Lost in a ball pit",
    "Self-portrait (you, in the morning)",
    "Jumping out of your skin",
    "Trimming your neighbour's bush",
    "You scratch my back, I'll scratch yours",
    "An abitious reach around",
    "Too much acid",
    "Armpit fetish",
    "Arseless chaps",
    "Your vegetable friend",
    "Suitcase aquarium",
    "Combing your hair with a hedgehog",
    "Tramp stamp",
    "The Hiemlich maneuver",
    "Dad dancing",
    "Centaur lollipop man",
    "Exploding cuckoo clock",
    "Florida Man",
    "Unicorn rainbow fart",
    "Pet rock",
    "Seeing a man about a horse",
    "The incredible Bouncing Boy (TM)",
    "Beer goggles",
    "Washing someone's mouth out with soap",
    "DIY lobotomy",
    "Trust excercises",
    "Tickle a pickle",
    "Clown police line-up",
    "Running away from your problems",
    "Awkward hug",
    "Questionable parenting",
    "An unfortunate birthmark",
    "Going batshit crazy",
    "Erotic oven mitts",
    "Gorilla panic",
    "The Fork Museum",
    "Foam party",
    "Up shit creek without a paddle",
    "Big girl's blouse",
    "Cat got your tongue",
    "Rubbernecking",
    "Talking shit",
    "Embarassing x-ray",
    "Stealing the covers",
    "Flesh Light",
    "Cheese nightmare",
    "1950's Sex Ed poster",
    "Bangkok Ping Pong Show",
    "Wiping the smile off your face",
    "Angry barbecue",
    "Octopus mating season",
    "Muffin top",
    "Sex bomb",
    "Bunny boiler",
    "Spooning a spoon",
    "Racist grandma",
    "Wet handshake",
    "Tinder creep",
    "Slow day at the box factory",
    "Monkey business",
    "Really ugly baby",
    "Karate chopping a frog",
    "Freestyle kazoo solo",
    "Going out in a blaze of glory",
    "Cannibal finger buffet",
    "Drowing in someone's eyes",
    "Lactose intolerance",
    "Making a bald-headed man cry",
    "LARPing",
    "Velociraptor Jesus",
    "Bronies",
    "Sore loser",
    "Freezing your own head",
    "Bingo wings",
    "I.T. rage",
    "Mobility scooter hit and run",
    "Terrified by butter",
    "Shotgun wedding",
    "Eyeball golf",
    "Banana hammock",
    "Cow tipping",
    "Builders breakdancing",
    "Joyless sex",
    "Stealing someone's thunder",
    "Lost in IKEA",
    "Throwing the baby out with the bathwater",
    "What really happened to the dinosaurs",
    "Beating around the bush",
    "Dutch oven",
    "A loving pat on the head",
    "The blind leading the blind",
    "You making love to the person opposite you",
    "OAP conga line",
    "Mangina",
    "Dark matter",
    "S.T.D. Appreciation Day",
    '"Kitten Mittens" (TM)',
    "Naked statue of yourself",
    "Crying over spilt milk",
    "Netflix and chill",
    "Making an arse out of yourself",
    "Beating up a jellyfish",
    "Going at it like rabbits",
    "Christmas dildo",
    "Potty mouth",
    "Minesweeping",
    "Eating roadkill",
    "Wheelbarrow race",
    "Gastric band",
    "Shouting at old people",
    "Walking into a mirror",
    "Mr. Floppy",
    "Riding a weasel",
    "Dreaming of bacon",
    "Dogs dressed as humans",
    "Pulling a hat out of a rabbit",
    "Glory hole surprise",
    "The Trump family",
    "Personal space invasion",
    "Some slight chafing",
    "Constipation",
    "Cream pie",
    "Edible panties",
    "Babe magnet",
    "Naked in a lift",
    "Back acne",
    "Eels, eels and more eels",
    "Wandering hands",
    "Touching cloth",
    "Meat sweats",
    "Life giving you lemons",
    "Freak show",
    "Scaring yourself shitless",
    "Booty call",
    "Raised by squirrels",
    "Drooling in your sleep",
    "Jazz hands",
    "Badly drawn on eyebrows",
    "Disappointing gravestone",
    "Crying on the inside",
    "A little slap and tickle",
    "Getting fingered by the law",
    "Popcorn surprise",
    "Skeleton in your closet",
    "Neckbeard",
    "Heavy breathing",
    "Eating spiderwebs",
    "Man spreading",
    "Darth Vader's day job",
    "Stamping on a child's sandcastle",
    "Monkey knife fight",
    "Touchy-feely geography teacher",
    "Giraffe limbo contest",
    "Packing a sausage",
    "Friendly camel toe",
    "Living in a skip",
    "Fainting goats",
    "T-Rex with a brand new handbag",
    "Rubbing someone up the wrong way",
    "Finger Lickin' Good!",
    "The duck face",
    "Moobs",
    "Sharknado",
    "Sexting",
    "Burger nips",
    "Shaving a llama",
    "Adopting a cactus",
    "The never-ending poo",
    "Death by salmon"
];